version: '2'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    # NOTE : For https
    # - /etc/letsencrypt/live/exapmle.com/cert.pem:/etc/nginx/cert.pem
    # - /etc/letsencrypt/live/exapmle.com/privkey.pem:/etc/nginx/private.pem
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
