version: '2'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    #NOTE : TLS key's path for HTTPS
    # - host.chain.key.pem path : nginx.conf's chain.key.pem path
    # - host.private.key.pem path : nginx.conf's private.key.pem path
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
